/**:
  ros__parameters:
    max_speed: 4.0 # m/s
    max_steer: 0.36 # rad (20°)
    angle_coef: 1.0 # coefficient pour l'angle de braquage
    range_angle: 160.0 # champ de vision en rad
    dist_critique: 2.0 # distance en dessous de laquelle on réduit la vitesse
    dist_secu: 0.3 # distance de sécurité latérale pour obstacle proche
    angle_decalage: 35.0 # angle de décalage pour obstacle proche
    distance_obst: 1.0 # distance en dessous de laquelle un obstacle est considéré proche
    range_angle_obst: 160.0 # champ de vision pour obstacle proche


    # Joystick indices for toggling mux OBSOLETE?
    auto_button_idx: 5 # R1 button  

